# OpenRouter API config
spring.application.name=tryingSpringBoot
spring.ai.openai.base-url=https://openrouter.ai/api

# OpenRouter Model Config
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.max-tokens=500
#spring.ai.openai.chat.options.model=google/gemini-2.0-flash - default model for all queries or model can be passed per query

